accounts/urls.py
from django.urls import path
from . import views


app_name = 'accounts'

urlpatterns = [
    path('', views.index, name='index'),
    path('login/', views.login, name='login'),
    path('signup/', views.signup, name='signup'),
    path('update/', views.update, name='update'),
    path('logout/', views.logout, name='logout'),
]

movies/urls.py
from django.urls import path
from . import views


app_name = 'movies'

urlpatterns = [
    path('', views.index, name='index'),
    path('create/', views.create, name='create'),
    path('<int:movie_pk>/', views.detail, name='detail'),
    path('<int:movie_pk>/delete/', views.delete, name='delete'),
    path('<int:movie_pk>/update/', views.update, name='update'),
    path('<int:pk>/reviews/', views.reviews_create, name='reviews_create'),
        path(
        '<int:movie_pk>/reviews/<int:review_pk>/delete/',
        views.reviews_delete,
        name='reviews_delete',
    ),
]

mypjt/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static
from accounts import views
urlpatterns = [
    path('admin/', admin.site.urls),
    path('movies/', include('movies.urls')),
    path('accounts/', include('accounts.urls')),
     path('<int:user_pk>/password/', views.change_password, name='change_password'),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

handler404 = 'movies.views.page_not_found'

accounts/models.py
from django.db import models
from django.contrib.auth.models import AbstractUser

# Create your models here.
class User(AbstractUser):
    pass

movies/models.py
from django.db import models
from django.conf import settings
# Create your models here.
class Movie(models.Model):
    user = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE)
    image = models.ImageField(blank=True, upload_to="%Y/%m/$d/")
    title = models.CharField(max_length=100)
    description = models.TextField()
    GENRE_CHOICES = [
        ('comedy', 'Comedy'),
        ('romance', 'Romance'),
        ('fantasy', 'Fantasy'),
    ]
    genre = models.CharField(max_length=100, choices=GENRE_CHOICES)
    score = models.FloatField()


class Review(models.Model):
    user = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE)
    movie = models.ForeignKey(Movie, on_delete=models.CASCADE)
    content = models.CharField(max_length=250)

accounts/forms.py
from django.contrib.auth import get_user_model
from django.contrib.auth.forms import UserCreationForm, UserChangeForm

class CustomUserCreationForm(UserCreationForm):
    
     class Meta(UserCreationForm.Meta):
        model = get_user_model()
class CustomUserChangeForm(UserChangeForm):
    password = None
    class Meta(UserChangeForm.Meta):
        
        model = get_user_model()
        fields = ('email','first_name','last_name','username',)

movies/forms.py
from django import forms
from .models import Movie, Review


class MovieForm(forms.ModelForm):

    class Meta:
        
        model = Movie
        exclude = ('user',)
        widgets = {
            'title': forms.TextInput(attrs={'class': 'form-control'}),
            'description': forms.Textarea(attrs={'class': 'form-control'}),
            'genre' : forms.Select(attrs={'class': 'form-control'}),
            'score': forms.NumberInput(attrs={'class': 'form-control', 'step': 0.5, 'min': 0, 'max': 5}),
        }   
class ReviewForm(forms.ModelForm):
    class Meta:
        model = Review
        fields = ('content',)

accounts/views.py
from django.shortcuts import render, redirect
from django.contrib.auth.forms import AuthenticationForm, PasswordChangeForm
from django.contrib.auth import login as auth_login
from django.contrib.auth import get_user_model
from django.contrib.auth import logout as auth_logout
from .forms import CustomUserCreationForm, CustomUserChangeForm
from django.contrib.auth import update_session_auth_hash
from django.contrib.auth.decorators import login_required


User = get_user_model()

# Create your views here.
def index(request):
    persons = User.objects.all()
    context = {
        'persons': persons
    }
    return render(request, 'movies/index.html', context)

def login(request):
    if request.user.is_authenticated:
        return redirect('movies:index')
    if request.method == 'POST':
        form = AuthenticationForm(request, request.POST)
        if form.is_valid():
            auth_login(request, form.get_user())
            return redirect('movies:index')
    else:
        form = AuthenticationForm()
    context = {
        'form': form
    }
    return render(request, 'accounts/login.html', context)

def signup(request):
    if request.user.is_authenticated:
        return redirect('movies:index')
    if request.method == 'POST':
        form = CustomUserCreationForm(request.POST)
        if form.is_valid():
            form.save()
            return redirect('movies:index')
    else:
        form = CustomUserCreationForm()
    context = {
        'form': form,
    }
    return render(request, 'accounts/signup.html', context)

@login_required
def logout(request):
    if request.method == 'POST':
        auth_logout(request)
        return redirect('accounts:login')
@login_required
def change_password(request, user_pk):
    if request.method == "POST":
        form = PasswordChangeForm(request.user, request.POST)
        if form.is_valid():
            user = form.save()
            update_session_auth_hash(request, user)
    else:
        form = PasswordChangeForm(request.user)
    
    context = {
        'form': form,
    }
    return render(request, 'accounts/change_password.html', context)

@login_required
def update(request):
    if request.method == "POST":
        form = CustomUserChangeForm(request.POST, instance= request.user)
        if form.is_valid():
            form.save()
            
            return redirect('movies:index')
    else:
        form = CustomUserChangeForm(instance=request.user)
        context = {
            'form': form,
        }
        return render(request, 'accounts/update.html', context)

movies/views.py
from django.shortcuts import render, redirect
from .models import Movie, Review
from .forms import MovieForm, ReviewForm
from django.contrib.auth.decorators import login_required
# Create your views here.
def index(request):
    movies = Movie.objects.all()
    context = {
        'movies': movies
    }
    return render(request, 'movies/index.html', context)

def create(request):
    if request.method == 'POST':
        form = MovieForm(request.POST, request.FILES)
        if form.is_valid():

            movie = form.save(commit=False)
            movie.user = request.user
            movie.save()
            return redirect('movies:detail', movie.pk)
    else:
        form = MovieForm()
    context = {
        'form': form
    }
    return render(request, 'movies/create.html', context)


    
def detail(request, movie_pk):
    movie = Movie.objects.get(pk=movie_pk)
    reviews = movie.review_set.all()
    review_form = ReviewForm()
    context = {
        'movie': movie,
        'review_form': review_form,
        'reviews': reviews,

    }
    return render(request, 'movies/detail.html', context)


def delete(request, movie_pk):
    movie = Movie.objects.get(pk=movie_pk)
    movie.delete()
    return redirect('movies:index')

def update(request, movie_pk):
    movie = Movie.objects.get(pk=movie_pk)
    if request.method == 'POST':

        form = MovieForm(request.POST, request.FILES, instance=movie)
        if form.is_valid():
            form.save()
            return redirect('movies:detail',movie.pk)
    else:
        form = MovieForm(instance=movie)
    context = {
        'movie': movie,
        'form': form
    }
    return render(request, 'movies/update.html', context)

@login_required
def reviews_create(request, pk):
    movie = Movie.objects.get(pk=pk)
    reviews = movie.review_set.all()
    review_form = ReviewForm(request.POST)
    if review_form.is_valid():
        review = review_form.save(commit=False)
        review.movie = movie
        review.user = request.user
        review.save()
        return redirect('movies:detail', movie.pk)
    context = {
        'review_form': review_form,
        'movie': movie,
        'reviews': reviews,
    }
    return render(request, 'movies/detail.html', context)


@login_required
def reviews_delete(request, movie_pk, review_pk):
    review = Review.objects.get(pk=review_pk)
    if request.user == review.user:
        review.delete()
    return redirect('movies:detail', movie_pk)

def page_not_found(request, exception):
    return render(request, 'movies/404.html', {})

accounts/templates/accounts/change_password.html
{% extends "base.html" %}

{% block content %}
  <h1>Password Change Page</h1>
  <form action="{% url "change_password" user.pk %}" method="POST">
    {% csrf_token %}
    {{ form.as_p }}
    <input type="submit" value="Password Change">
  </form>
{% endblock content %}

accounts/templates/accounts/login.html
{% extends 'base.html' %}

{% block content %}
  <h1>LOGIN Page</h1>
  <form method="POST">
    {% csrf_token %}
    {{ form.as_p }}
    <input type="submit" value="LOGIN">
  </form>
{% endblock content %}

accounts/templates/accounts/signup.html
{% extends 'base.html' %}

{% block content %}
  <h1>Sign Up Page</h1>
  <form method="POST">
    {% csrf_token %}
    {{ form.as_p }}
    <input type="submit" value="Sign up">
  </form>
{% endblock content %}

accounts/templates/accounts/update.html
{% extends "base.html" %}

{% block content %}
  <h1>Update Page</h1>
  <form action="{% url "accounts:update" %}" method="POST">
    {% csrf_token %}
    {{ form.as_p }}
    <input type="submit" value="Update">
  </form>

  <form action="{% url "change_password" user.pk %}" method="POST">
    {% csrf_token %}
    <input type="submit" value="비밀번호 변경">
{% endblock content %}

movies/templates/movies/create.html
{% extends "base.html" %}

{% block content %}
  <h1>이 곳에서 할 일을 생성합니다.</h1>

  <form action="{% url "movies:create" %}" method="POST" enctype="multipart/form-data">
    {% csrf_token %}
    {{ form.as_p }}
    <input type="submit" value="제출">
  </form>
{% endblock content %}

movies/templates/movies/detail.html
{% extends "base.html" %}
{% load static %}
{% block content %}
  {% if movie.image %}
    <img src="{{ movie.image.url }}" alt="poster" width="100%" height="500px">
  {% else %}  
  <img src="{% static 'noimage.png' %}" alt="noimage" class="img-fluid">
  {% endif %}
  <h1>DETAIL PAGE</h1>
  <hr>
  <h2>제 목 : {{ movie.title }}</h2>
  <p>내 용 : {{ movie.description }}</p>
  <p>장 르 : {{ movie.genre }}</p>
  <p>평 점 : {{ movie.score }}</p>
  <hr>
  {% if request.user == movie.user %}
  <div class="d-flex flex-nowrap">
    <a href="{% url "movies:update" movie.pk %}" class="btn btn-primary me-2">Update</a>
  <form action="{% url "movies:delete" movie.pk %}" method="POST">
    {% csrf_token %}
    <input class="btn btn-danger" type="submit" value="DELETE">
  </form>
  </div>
  <hr>
  {% endif %}

  <h3>Reviews</h3>
  <div>
    
  </div>
  <ul class="list-group">
    {% for review in reviews %}
      <li class="list-group-item">
        <div class="d-flex justify-content-between">
          <div>
            {{review.user}} - {{ review.content }}
          </div>
          {% if request.user == review.user %}
          <div>
            <form action="{% url "movies:reviews_delete" movie.pk review.pk %}" method="POST">
              {% csrf_token %}
              <input class="btn btn-danger" type="submit" value="DELETE">
            </form>
          </div>
          {% endif %}
        </div>
      </li>
    {% endfor %}
  </ul>
  <div class="mt-3">
    <form action="{% url "movies:reviews_create" movie.pk %}" method="POST">
      {% csrf_token %}
      {{ review_form }}
      <input type="submit" value="리뷰 작성">
    </form>
  </div>
  <hr>
  
  <a href="{% url "movies:index" %}" class="btn btn-primary">BACK</a>
{% endblock content %}

movies/templates/movies/index.html
{% extends "base.html" %}
{% load static %}
{% block content %}
  <h1>INDEX PAGE</h1>
  <ul>
    <div class="row row-cols-1 row-cols-md-2 row-cols-lg-3 g-4">
      {% for movie in movies %}
      <div class="col" >
        <div class="card mb-3" style="max-width: 540px;">
          <h5 class="card-header">{{ movie.title }}</h5>
          {% comment %} {% if movie.image %}
            <img src="{{ movie.image.url }}"  height="600px" alt="poster">
          {% else %}  
            <img src="{% static 'noimage.png' %}" alt="noimage" height="600px">
          {% endif %} {% endcomment %}
          <div class="card-body">
            <p class="card-text">{{movie.description}}</p>
            <a href="{% url "movies:detail" movie.pk %}" class="btn btn-primary">Detail</a>
          </div>
        </div>
      </div>
      {% endfor %}
    </div>
    {% comment %} {% for movie in movies %}
    <a href="{% url 'movies:detail' movie.pk%}">
      {% if movie.image %}
        <img src="{{ movie.image.url }}" alt="poster">
      {% else %}  
        <img src="{% static 'noimage.png' %}" alt="noimage" style="max-width: 200px; max-height:200px;">
      {% endif %}
      <p>{{ movie.title }}</p>
    </a>
    <hr> {% endcomment %}

  </ul>
{% endblock content %}

movies/templates/movies/update.html
{% extends "base.html" %}

{% block content %}
  <h1>Update</h1>

  <form action="{% url "movies:update" movie.pk %}" method="POST" enctype="multipart/form-data">
    {% csrf_token %}
    {{ form.as_p }}
    <input type="submit" value="제출">
  </form>
{% endblock content %}

templates/base.html
{% load static %}

<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <title>Document</title>
  <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-9ndCyUaIbzAi2FUVXJi0CjmCapSmO7SnpJef0486qhLnuZ2cdeRhO02iuK6FUUVM" crossorigin="anonymous">
</head>
<body>
  <nav class="navbar navbar-expand-lg bg-dark border-bottom border-body" data-bs-theme="dark">
    <div class="container-fluid">
      <a class="navbar-brand" href="#">SSAFY</a>
      <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
      </button>
      <div class="collapse navbar-collapse" id="navbarSupportedContent">
        <ul class="navbar-nav me-auto mb-2 mb-lg-0">
          <li class="nav-item">
            <a class="nav-link active" aria-current="page" href="{% url "movies:index" %}">INDEX</a>
          </li>
          {% if request.user.is_authenticated %}
            <li class="nav-item">
              <a class="nav-link" href="{% url "movies:create" %}">CREATE</a>
            </li>
            <li class="nav-item">
              <a class="nav-link" href="{% url "accounts:update" %}">회원정보수정</a>
            </li>
            <li class="nav-item">
              <a class="nav-link" href="{% url "change_password" user.pk%} ">비밀번호 변경</a>
            </li>
            <form action="{% url "accounts:logout" %}" method="POST">
              {% csrf_token %}
              <input class="nav-link"  type="submit" value="로그아웃">
              {% comment %} <button class="btn btn-outline-dark" type="submit">[로그아웃]</button> {% endcomment %}
            </form>
          {% else %}
            <li class="nav-item">
              <a class="nav-link" href="{% url "accounts:login" %}">로그인</a>
            </li>
            <li class="nav-item">
              <a class="nav-link" href="{% url "accounts:signup" %}">회원가입</a>
            </li>
          {% endif %}
        </ul>
      </div>
    </div>
  </nav>
  {% comment %} <p>SSAFY</p>
  <a href="{% url "movies:index" %}">[INDEX]</a>
  {% if request.user.is_authenticated %}
  <a href="{% url "movies:create" %}">[CREATE]</a>
  <a href="{% url "accounts:update" %}">[회원정보수정]</a>
  
  <form action="{% url "accounts:logout" %}" method="POST">
    {% csrf_token %}
    <input type="submit" value="[로그아웃]">
  </form>
  {% else %}
    <a href="{% url "accounts:login" %}">[로그인]</a>
    <a href="{% url "accounts:signup" %}">[회원가입]</a>
  {% endif %} {% endcomment %}
  <div class="container">
    {% block content %}
    {% endblock content %}
  </div>
  <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0/dist/js/bootstrap.bundle.min.js" integrity="sha384-geWF76RCwLtnZ8qwWowPQNguL3RmwHVBC9FhGdlKrxdiJJigb/j/68SIy3Te4Bkz" crossorigin="anonymous"></script>
</body>
</html>